name: snowflakeDemo
profile: snowflake-demo
version: '2.0'

analysis-paths:
- analysis
clean-targets:
- target
- dbt_modules
data-paths:
- data
macro-paths:
- macros
source-paths:
- models
test-paths:
- tests
target-path: target

models:
  snowflakeDemo:
    load:
      schema: "VLT"
      enabled: true
      materialized: incremental
      stage:
        schema: "STG"
        enabled: true
        materialized: view
      raw:
        schema: "RAW"
        enabled: true
        materialized: incremental
  vars:
    date: TO_DATE('1992-01-08')
    hash: SHA # or MD5